package:
  name: auto-enaml
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - enaml
    - atom

test:
  imports:
    - auto_enaml
#    Something about auto_enaml's fancy imports might be confusing conda's
#    testing procedure. These imports work find in conda-installed auto_enaml,
#    but they fail here. We are ignoring this and moving on for now.
#    - auto_enaml.api
#    - auto_enaml.auto_view
#    - auto_enaml.utils
